### ISSUE TITLE
few question regarding to vscode-docker

### ISSUE THREAD

**Issue by leetskil** [tiibun/vscode-docker-ws#2]
can i edit/create/delete file folder? when using vscode docker extension. thanks

**Comment by tiibun** [comment]
Yes, but I had a problem so released 0.0.3.
I confirmed on docker for mac with a Debian docker container.
If you can't do, let me know.

thanks.

**Comment by leetskil** [comment]
i've installed the extension but i dont know how to connect docker to vscode using your extension.

**Comment by tiibun** [comment]
What's your host's OS?
I have confirmed on Mac for Docker only yet.

1. Is a Docker container running?
```
docker  run -d ...
```
or
```
docker-compose up -d
```

2. Select VSCode menu [View] -> [Command Pallete] ( or [Cmd + Shift + P] or [F1] )
And select `DockerWS: Add Docker Folder To Workspace`

It will be shown running docker containers.
so select a docker container to connect.

If error is happend, please tell me error messages.

**Comment by leetskil** [comment]
oh i see. i'm running in windows 10 pro *bummer 

hope you can integrate it in windowsOS. 

great extension! 

thanks

**Comment by tiibun** [comment]
Which do you use Docker for Windows or Docker toolkit?

**Comment by leetskil** [comment]
i use docker in virtualbox ubuntu 16.04

**Comment by tiibun** [comment]
Thanks, and do you use docker-machine?

**Comment by tiibun** [comment]
I have released v0.1.0 for docker host configuration.
Could you try this?

1. You must enable Docker Remote API
from https://docs.docker.com/install/linux/linux-postinstall/#configuring-remote-access-with-systemd-unit-file

```
# on ubuntu 18.04
$ sudo systemctl edit docker.service

[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 # allow from any hosts

$ sudo systemctl daemon-reload
$ sudo systemctl restart docker.service
```
If VirtualBox networking is NAT, port forwarding 2375 in VirtualBox network setting.

Confirm to connect docker daemon from Windows.
```
docker -H tcp://(Ubuntu IP address):2375 ps
```
In case of use port forwarding,
```
docker -H tcp://127.0.0.1:2375 ps
```

2. VSCode settings

Find `Docker WS Host`, and set `(Ubuntu IP address):2375` or `127.0.0.1:2375`(NAT port forward)

3. Add Docker folder to workspace!

**Comment by Midacts** [comment]
I'm running Windows 10 with VSCode and Docker for Windows.

I am able to open the docker container as a workspace in VSCode, but it __does not allow me to save the file via VSCode__.

Any suggestions?

**Comment by tiibun** [comment]
@Midacts 
Do you have a permission for save the file ?
What is your docker image OS ?
I can advise if you tell me detailed information.

**Comment by Midacts** [comment]
I have tried opening vscode as admin.

It's a debian9 container.

Maybe it is because I'm running vscode as my windows account and the
container is running as root?

I can provide whatever additional information that is required.

**Comment by Rann1** [comment]
I'm currently also trying the same, I can connect to the docker (running Ubuntu) from my Windows machine, and I can see the files, but it does not allow editing and saving a file (permissions error)

**Comment by Midacts** [comment]
Correct. That's what I am running into.

**Comment by tiibun** [comment]
@Midacts 
I found a bug on windows, so I've released ver 0.2.0.
Could you update the extension, and try write a file?

**Comment by Rann1** [comment]
Fixed, thanks!

**Comment by Midacts** [comment]
Your latest change fixed the issue. Thanks!

I spun up a alpine:latest container
Opened VS Code and added the docker folder to the workspace
added a line in the `/etc/hosts` file via VS code and was able to save it.

I then went on the container and verified the line was there.
